<?php

namespace Tests\Feature;

use App\Models\Thread;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ReadThreads extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $response = $this->get('/');
        $response->assertStatus(200);
    }

    public function testUserCanBrowseThreads()
    {
        $thread = $this->thread; //在setUp方法中自动创建了一条thread记录
        $this->get('/threads')
            ->assertSee($this->thread->title); //断言响应中会看到这个标题
    }

    public function testUserCanReadSingleThread()
    {
        $thread = $this->thread;
        $this->get('/threads/' . $this->thread->id)
            ->assertSee($this->thread->title);
    }

    public function testUserCanReadRepliesIFTheyHave()
    {
        /**
         * 如果存在thread
         * 并且thread有回复
         * 那么当我们看到thread时
         * 我们也要看到回复
         */
        $reply = factory('App\Models\Reply')->create(['thread_id'=>$this->thread->id]);
        $this->get('/threads/' . $this->thread->id)->assertSee($reply->body);
    }


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Models\Thread')->create();
    }
}
