<?php

namespace Tests\Feature;

use App\Models\Thread;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ReadThreadsTest extends TestCase
{
    protected $thread;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Models\Thread')->create();
    }

    public function testBasicTest()
    {
        $response = $this->get('/');
        $response->assertStatus(200);
    }

    public function testUserCanBrowseThreads()
    {
        $thread = $this->thread; //在setUp方法中自动创建了一条thread记录
        $this->get('/threads')
            ->assertSee($this->thread->title); //断言响应中会看到这个标题
    }

    public function testUserCanReadSingleThread()
    {
        $thread = $this->thread;
        $this->get('/threads/' . $this->thread->id)
            ->assertSee($this->thread->title);
    }

    public function testUserCanReadRepliesIFTheyHave()
    {
        /**
         * 如果存在thread
         * 并且thread有回复
         * 那么当我们看到thread时
         * 我们也要看到回复
         */
        $reply = factory('App\Models\Reply')->create(['thread_id'=>$this->thread->id]);
        $this->get('/threads/' . $this->thread->id)->assertSee($reply->body);
    }

    //用户可以根据分类过滤帖子
    public function testUserCanFilterThreadsAccordingToACategory()
    {
        $category = factory('App\Models\Category')->create();
        $threadInCategory = factory('App\Models\Thread')->create(['category_id'=>$category->id]);
        $threadNotInCategory = factory('App\Models\Thread')->create();
        $this->get('/categories/'.$category->id)
            ->assertSee($threadInCategory->title)
            ->assertDontSee($threadNotInCategory->title);
    }

}
